const { ROLES } = require('./roles');

const PERMISSIONS = {
  // User Management
  MANAGE_USERS: [ROLES.ADMIN],
  APPROVE_USERS: [ROLES.ADMIN],
  VIEW_USERS: [ROLES.ADMIN],

  // Company Settings
  MANAGE_COMPANY: [ROLES.ADMIN],
  VIEW_COMPANY: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],

  // Masters (Customers, Products, Factories, Ports, etc.)
  MANAGE_MASTERS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  VIEW_MASTERS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],
  MANAGE_CUSTOMERS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],

  // Quotations
  CREATE_QUOTATION: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],
  EDIT_QUOTATION: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],
  VIEW_QUOTATION: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],
  DELETE_QUOTATION: [ROLES.ADMIN],

  // Shipments
  CREATE_SHIPMENT: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES], // Sales converts quote to shipment
  EDIT_SHIPMENT: [ROLES.ADMIN, ROLES.SUPERVISOR],
  VIEW_SHIPMENT: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],
  DELETE_SHIPMENT: [ROLES.ADMIN],

  // Documents
  GENERATE_DOCUMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  VIEW_DOCUMENTS: [ROLES.ADMIN, ROLES.SUPERVISOR, ROLES.SALES],

  // Audit & System
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.SUPERVISOR],
  VIEW_AUDIT_LOGS: [ROLES.ADMIN],
  MANAGE_BACKUP: [ROLES.ADMIN],
};

module.exports = PERMISSIONS;
